package seed

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/Linux-DEX/azstorecli/internal/storage"
	"github.com/Linux-DEX/azstorecli/internal/util"
)

// dumpInlineLimit is the size below which a blob's content is written
// inline into the YAML rather than as a fixture file. Small JSON
// fixtures read better inline; anything larger belongs in its own file
// so the seed document stays reviewable.
const dumpInlineLimit = 512

// Dump reverses Apply: it reads live storage and writes a seed document
// plus its fixtures, so a state built up by hand can be committed.
func Dump(ctx context.Context, c *storage.Clients, outDir string) (*Doc, error) {
	if err := os.MkdirAll(filepath.Join(outDir, "fixtures"), 0o755); err != nil {
		return nil, err
	}
	doc := &Doc{Version: 1, dir: outDir}

	containers, err := c.ListContainers(ctx)
	if err != nil {
		return nil, err
	}
	for _, ci := range containers {
		// $logs and friends are service-managed; seeding them back is
		// both impossible and meaningless.
		if strings.HasPrefix(ci.Name, "$") {
			continue
		}
		out := Container{Name: ci.Name, Access: ci.Access}

		marker := ""
		for {
			page, err := c.ListBlobsFlat(ctx, ci.Name, "", marker, 500)
			if err != nil {
				return nil, err
			}
			for _, e := range page.Entries {
				if e.IsDir {
					continue
				}
				b, err := dumpBlob(ctx, c, ci.Name, e, outDir)
				if err != nil {
					return nil, err
				}
				out.Blobs = append(out.Blobs, b)
			}
			if page.Marker == "" {
				break
			}
			marker = page.Marker
		}
		doc.Blob.Containers = append(doc.Blob.Containers, out)
	}

	queues, err := c.ListQueues(ctx)
	if err == nil {
		for _, qi := range queues {
			q := Queue{Name: qi.Name}
			msgs, err := c.PeekMessages(ctx, qi.Name, 32)
			if err != nil {
				continue
			}
			for _, m := range msgs {
				q.Messages = append(q.Messages, QueueMsg{Body: m.Body, Base64: m.Base64Encoded})
			}
			doc.Queue.Queues = append(doc.Queue.Queues, q)
		}
	}

	tables, err := c.ListTables(ctx)
	if err == nil {
		for _, ti := range tables {
			t := Table{Name: ti.Name}
			token := ""
			for {
				page, err := c.QueryEntities(ctx, ti.Name, "", token, 500)
				if err != nil {
					break
				}
				for _, e := range page.Entities {
					t.Entities = append(t.Entities, e.Properties)
				}
				if page.Token == "" {
					break
				}
				token = page.Token
			}
			doc.Table.Tables = append(doc.Table.Tables, t)
		}
	}

	data, err := yaml.Marshal(doc)
	if err != nil {
		return nil, err
	}
	header := "# Generated by `azstore seed dump`. Safe to edit and commit.\n"
	if err := util.WriteAtomic(filepath.Join(outDir, "containers.yaml"), append([]byte(header), data...), 0o644); err != nil {
		return nil, err
	}
	return doc, nil
}

func dumpBlob(ctx context.Context, c *storage.Clients, container string, e storage.BlobEntry, outDir string) (Blob, error) {
	b := Blob{Name: e.Name, ContentType: e.ContentType}

	props, err := c.Properties(ctx, container, e.Name)
	if err == nil && len(props.Metadata) > 0 {
		b.Metadata = props.Metadata
	}

	if e.Size <= dumpInlineLimit {
		data, truncated, err := c.ReadRange(ctx, container, e.Name, dumpInlineLimit)
		if err != nil {
			return b, err
		}
		if !truncated && isText(data) {
			b.Content = string(data)
			return b, nil
		}
	}

	rel := filepath.Join("fixtures", fixtureName(e.Name))
	dst := filepath.Join(outDir, rel)
	if _, err := c.DownloadToFile(ctx, container, e.Name, dst); err != nil {
		return b, err
	}
	b.File = filepath.ToSlash(rel)
	return b, nil
}

// fixtureName flattens a blob name into a filename, keeping the prefix
// visible so two blobs with the same leaf do not collide.
func fixtureName(blobName string) string {
	return strings.ReplaceAll(strings.TrimPrefix(blobName, "/"), "/", "__")
}

// isText reports whether data is safe to embed in YAML.
func isText(data []byte) bool {
	if len(data) == 0 {
		return false
	}
	for _, b := range data {
		if b == 0 {
			return false
		}
	}
	return true
}

// DefaultPath is the conventional seed file inside a project.
func DefaultPath(projectDir string) string {
	return filepath.Join(projectDir, ".azstorecli", "seed", "containers.yaml")
}

// Describe renders a one-line summary of a document, for confirmation
// prompts.
func (d *Doc) Describe() string {
	blobs := 0
	for _, c := range d.Blob.Containers {
		blobs += len(c.Blobs)
	}
	msgs := 0
	for _, q := range d.Queue.Queues {
		msgs += len(q.Messages)
	}
	entities := 0
	for _, t := range d.Table.Tables {
		entities += len(t.Entities)
	}
	return fmt.Sprintf("%d containers / %d blobs · %d queues / %d messages · %d tables / %d entities",
		len(d.Blob.Containers), blobs, len(d.Queue.Queues), msgs, len(d.Table.Tables), entities)
}
